[build]
ignore = ["node", "npm", "yarn", "pnpm"]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[variables]
PHP_VERSION = "8.3"
PHP_EXTENSIONS = "gd zip"
